breadthFirstSearch: 
	gcc main.c breadth-first-search.c ./adjacency-list/adjacency-list.c ./array-queue/queue.c ./adjacency-list/tailed-singly-linked-list/tailed-singly-linked-list.c tests.c -o a.out
